### ISSUE TITLE
Looks like a child wrote the `index.ts`

### ISSUE THREAD

**Issue by kevinmarquesp** [kevinmarquesp/blog#7]
The `updatePostsTable()` was doing:

1. Generating a path based on url string
2. Fetching the file from that url
3. And filling the `$postsTable` with that info...

Also, where is the comments? Why this function is returning a weird type?

### Todos

- [ ] Make a function to fetch the JSON and return the object
- [ ] Make a type template for that object
- [ ] Generate the URL based on a year value
- [ ] Update the `$postsTable` element aftar that
